language: cpp

os:
  - linux
  - osx

env:
  matrix:
    - NODE_VERSION="10"
    - NODE_VERSION="11"
    - NODE_VERSION="12"
    - NODE_VERSION="13"
    - NODE_VERSION="14"
    - NODE_VERSION="15"
    - NODE_VERSION="16"

  global:
    - secure: "qcCCx495V8ocKfd2fRhhbWR61rVdBBf2SVcAIhKQuGc/UluzoT4ctAEqs9J6C0bBW//wPFE6xwaegQ27+e6bcOqwSjKHFDOb+P75/qMqagVms+iftEbLlXQQrZPu7sT8uLb8Aqll+fz5UrgZuEZV1zS92rwKqEcchlbHYRWNbRUPWmItiUZdxxYL3bt7M8RwMBFals7iaqRrru4urSaWHscbZ5czGewfRXW4w1uT6Q9+52QH07SH/zJMppGrSFJKO3Bk7vQgo+657T7sw5pGKjH1JX/jUpKCKDelgPZ48E/ZV1bNsmMoH5tcNKBEJQmJBfFZjdvTWvZ4Huwk9Lyc5i3OREWD4v4qDGPDs36lVBnLjnBvkekpWkxRa7O87hQ77v5LU17f7pwEFBntYm/MQdBJshyxiivDQIf7VqByeuUTn370tOZ3DqZpwtCyFJRcLFLxp3rSXsC+zR0HeW3/bS5EVNByTHy4FHefkCMO3mCMj7miQ7X5fwixxDDl+srzHsR3rvQkMlpPMvBvSWul+tznAJV+N3cK7KrV3tT1PRYBi+pzA5JnBoSMdfF0BhWaPnf7YN53vy62GB8oy0azEb0AHmXCX1p6RcS5iNM44mk8GCXYKz8le1wmlYodSgo/hMxuOc9JnAlgsbhRexTYpErlfOUs58RdNDf1ImO54U4="
    - secure: "Oi/pws08wfmxUpJB2ECb9LisFLqNfutmi2XHWRnPZjH3T4bnctTm2tJTcZC9DTeUwa6HQy+GmBe30ybKKWEjF6U77q7ljfAUM6Ky/w1BAb/TLnDXfophM39qE6GJsxO81iB6d8WYE6HRZftwnJWqA26oMz2AdE5l7ayBds0dwnhHFtRn+f2zNuG2AZoxMEUWvngPHR9wAHaddHpKs2vnZdXXQOkKm+U4vouqyd0pkayjx1Nq09GrWEe/bjs6RV5YAL1mpdvxA8i87bX8DqmwyE2le2HYaWNysF53eJe8baCU21LKkbnl1EJfPvpbbs8lagoitnhq5fZHuoPEajHw0D/uy7oR7f3M6InqKTqAWFcSFsF2e6CyxHKHbL82KGi5cDxak6bZNZsjoR57IchS3pANEkAqBzHl776KALPpw9aVbiwgbPV96/NdVSZaAE58WW2xQjmUBUh6Ns2bQWa9GsGvG7wHEUx7gQNtiicpwWDvlPjiSj06uqWHyiPJrNxI07r3uFTKZJtChqkoKX8COxhr7jWrWlzfIOU0tjBJKUochLvVoe3+LLVSJRis7f8g72R5KE4dDPYBHM/NVqsi1sQFGhHOsRB2yZMowEwV/1e/q18jrOe0G8srYG7XJABPPQZaf1R9Y8PjJon+FvfuqtlCjQOz1I5XHrngGceoX3o="


sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

before_install:
  - export CXX=g++
  - export CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-9 CXX=g++-9; fi
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - export PATH=$(pwd)/node_modules/.bin:${PATH}

install:
  - npm install --build-from-source

script:
  - node --version
  - npm --version
  - npm test
  - node example.js
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then node-pre-gyp package unpublish publish info; fi;
